name: "Feed Generator"
author: "Frandel Wanjawa"
description: "feed generator for podcasts"
runs:
  using : "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"

inputs:
  email:
    description: commit's source email
    required: true
    default: ${{github.actor}}@localhost

  name:
    description: commit's source name
    required: true
    default: ${{github.actor}}
